services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4815
      POSTGRES_DB: scudsystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:4815@db:5432/scudsystem"
      JWT_SECRET: "secret_key"
      FIRESEC_API_KEY: "YOUR_FIRESEC_KEY"
      FRONTEND_URL: "http://localhost:3000"
    ports:
      - "3001:3001"
      - "5555:5555"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    depends_on:
      - backend
    environment:
      NEXT_PUBLIC_API_URL: "http://localhost:3001"
    ports:
      - "3000:3000"

volumes:
  postgres_data:
  uploads_data: 