services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4815
      POSTGRES_DB: scudsystem
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:4815@db:5432/scudsystem"
      JWT_SECRET: "secret_key"
      FIRESEC_API_KEY: "YOUR_FIRESEC_KEY"
    ports:
      - "3001:3001"
    volumes:
      - uploads_data:/app/uploads

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"

  # caddy:
  #   image: caddy:2
  #   restart: always
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./Caddyfile:/etc/caddy/Caddyfile
  #     - caddy_data:/data
  #     - caddy_config:/config
  #   depends_on:
  #     - frontend

volumes:
  postgres_data:
  uploads_data:
  caddy_data:
  caddy_config:
